import Head from 'next/head';
import { motion as m } from 'framer-motion';

export default function Home() {
  return (
    <m.div
      initial={{ x: '100%' }}
      animate={{ x: '0%' }}
      exit={{ opacity: 1 }}
      transition={{ duration: 0.6, ease: 'easeOut' }}
      className='text-gray-900 absolute top-0 left-0 w-full h-full bg-orange-100 lg:px-48 px-16'
    >
      <Head>
        <title>Valmar's Portfolio page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='my-96 p-1'>
          <h1
            animate={{ y: 0 }}
            initial={{ y: '100%' }}
            className='text-6xl text-center lg:text-right lg:text-9xl'
          >
            Valmar Parts
          </h1>
        </div>
        <div className='flex justify-between'>
          <div>
            <h2>Applied Computer Science Student</h2>
            <h2>Front-end development focused</h2>
            <h2>2023</h2>
          </div>
          <div>
            <h3>student life intro</h3>
            <h3>hobbies</h3>
            <h3>personal life</h3>
          </div>
        </div>
      </main>
    </m.div>
  );
}
